GitHub workflow configuration to deploy static assets
cere-io/cere-games-sdk pull request #80
Opened 2023-05-16 07:05 UTC by skambalin

> _The goal of the pull request is not only to propose a working code as a solution to the requirement.  
> It is a tool for you to give context and explanation of your approach to the problem,  
> and transfer the knowledge to your team members._

## Checklist (Mandatory):

- [x] I have a ticket for this PR ([link](https://www.notion.so/cere/Add-WDIO-test-runs-configuration-to-Game-SDK-CI-d82bc3b81a014fda8c39c1fc3b0e33e9?pvs=4))
- [ ] I have added a record to the `CHANGELOG.md`
- [ ] I have tested new code locally
- [ ] I have done a smoke test of the larger feature locally
- [x] I have merged the `dev` (parent) branch into my feature branch and resolved all conflicts
- [ ] I have added tests that prove my fix/implementation is effective or that my feature works

## Checklist (Optional):

- [x] I have written the code according to the adopted [style guide](https://github.com/cere-io/fe-guidelines)?

## Additional notes

- Add env files and workflows configuration for each env

2023-05-16 07:32 UTC, evgeny-s approved these changes

2023-05-30 17:51 UTC, krolol requested changes

2023-05-30 17:51 UTC, krolol commented on .github/workflows/dev.yaml
> +      s3_bucket_name: 'games-sdk.core-dev.aws.cere.io'
games-sdk-dev.core-dev.aws.cere.io

2023-05-30 17:51 UTC, krolol commented on .github/workflows/stage.yaml
> +      s3_bucket_name: 'games-sdk.core-stage.aws.cere.io'
games-sdk-stg.core-stage.aws.cere.io

2023-06-01 03:43 UTC, skambalin commented on .github/workflows/dev.yaml
> +      s3_bucket_name: 'games-sdk.core-dev.aws.cere.io'
Updated

2023-06-01 03:43 UTC, skambalin commented on .github/workflows/stage.yaml
> +      s3_bucket_name: 'games-sdk.core-stage.aws.cere.io'
Updated

2023-06-01 04:15 UTC, merged